version: "3.5"

services:
  api:
    build: ./api
    command: nodemon server.js
    volumes:
      - ./api:/app
    ports:
      - "8080:8080"
  data-service:
    build: ./data-service
    command: dotnet watch run --configuration Debug
    volumes:
      - ./data-service:/app
    ports:
      - "8081:80"